package com.example.fcs.enums;

public class Enums {
    public enum VehicleType{
        PETROL, EV
    }

    public enum FuelType{
        L, eV
    }

    public enum VehicleTypes{
        CAR, SCOOTER, TRUCK, BIKE
    }

    public enum ExpenseType{
        CAR_WASH, FINANCING, FINE, PARKING, PAYMENT, REGISTRATION, REIMBURSEMENT, TAX, TOLLS
    }

    public enum Reason{
        WORK, TRIP
    }

    public enum ServiceType{
        AIR_CONDITIONING, AIR_FILTER, BATTERY, BELTS, BODY_OR_CHASSIS, BRAKE_FLUID, BRAKE_PAD, BRAKE_REPLACEMENT, CABIN_AIR_FILLER,
        CLUTCH_FLUID, CLUTCH_SYSTEM, COOLING_SYSTEM, ENGINE_REPAIR, EXHAUST_SYSTEM, FUEL_FILLER, FUEL_PUMP, GLASS_OR_MIRRORS,
        HEATING_SYSTEM, HORN, INSPECTION, LABOR_COST, LIGHTS, NEW_TIRES, OIL_CHANGE, OIL_FILTER, RADIATOR, ROTATE_TIRES,
        SEAT_TIRES, SEAT_BELT, SPARK_PLUGS, STEERING_SYSTEM, SUSPENSION_SYSTEM, TECHNICAL_CONTROL, TIRE_PRESSURE,
        TRANSMISSION_FLUID, WHEEL_ALIGNMENT, WINDSHIELD_WIPERS
    }

    public enum IncomeType{
        FREIGHT, REFUND, RIDE, TRANSPORT_APPLICATION, VEHICLE_SALE
    }
}
